name: ezpz
channels:
    - conda-forge
dependencies:
  - python>=3.6
  - jupyter>=1.0
  - requests
  - numpy>=1.21
  - networkx
  - matplotlib
  - graphviz
  - stanza==1.1.1
  - pip
  - pip:
    - tuw_nlp @ git+https://github.com/recski/tuw-nlp@dev#egg=tuw_nlp
    - POTATO @ git+https://github.com/adaamko/POTATO@dev#egg=POTATO
